### ISSUE TITLE
[Backend - API - Criar Publicação] Como um usuário, quero poder criar publicações no blog.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/SQUAD-14#1]
***Descrição:***
O sistema deve permitir que qualquer pessoa crie publicações. Cada publicação deve ter um título e um conteúdo. As publicações devem ser validadas para garantir que ambos os campos estão preenchidos antes de serem salvos no banco de dados.

***Critérios de Aceitação:***

- A API deve aceitar uma requisição POST com título e conteúdo.
- A API deve validar que nem o título nem o conteúdo estejam vazios.
- A API deve retornar a postagem criado com um identificador único (ID).

***Tasks:***

- [x]  Definir o modelo de dados para as postagens.
    - [x]  Criar banco de dado com a tabela necessária (Pode ser por ORM)
    - [x]  Criar Entidade
    - [x]  Criar DTO para a requisição (opcional)
- [x]  Implementar o endpoint POST para criação de postagens.
    - [x]  Criar um repositório com o método necessário;
    - [x]  Criar um serviço com o método necessário;
    - [x]  Criar controller com o endpoint necessário.
- [x]  Implementar validações para título e conteúdo.
- [x]  Atualizar a documentação da API.
