### ISSUE TITLE
[Backend - API - Criar Comentário] Como um usuário, quero poder criar comentários em uma publicação.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/SQUAD-14#11]
**Descrição:**
O sistema deve permitir que qualquer pessoa crie comentários em uma publicação específica. Cada comentário deve ter um conteúdo e estar associado a uma publicação. Os comentários devem ser validados para garantir que o conteúdo está preenchido antes de serem salvos no banco de dados.

**Critérios de Aceitação:**

- A API deve aceitar uma requisição POST com o ID da publicação e o conteúdo do comentário.
- A API deve validar que o conteúdo não está vazio.
- A API deve retornar o comentário criado com um identificador único (ID) e o ID da publicação associada.

**Tasks:**

- [x]  Definir o modelo de dados para os comentários.
    - [x]  Criar banco de dados com a tabela necessária (pode ser por ORM).
    - [x]  Criar Entidade.
    - [x]  Criar DTO para a requisição (opcional).
- [x]  Implementar o endpoint POST para criação de comentários.
    - [x]  Criar um repositório com o método necessário.
    - [x]  Criar um serviço com o método necessário.
    - [x]  Criar controller com o endpoint necessário.
    - [x]  Implementar validações para o conteúdo.
- [x]  Atualizar a documentação da API.
