### ISSUE TITLE
[Backend - API - Obter um Comentário] Como um usuário, quero ver detalhes de um comentário específico.

### ISSUE THREAD

**Issue by 1Jeferson** [Hanami-Staff/SQUAD-14#13]
**Descrição:**
O sistema deve permitir que qualquer pessoa visualize detalhes de um comentário específico existente. A listagem deve incluir campos com mais detalhes do comentário.

**Critérios de Aceitação:**

- A API deve aceitar uma requisição GET para listar um comentário de um ID específico.
- A API deve retornar o comentário escolhido com os detalhes.

**Tasks:**

- [x]  Criar DTO para a requisição (opcional).
- [x]  Implementar o endpoint GET para obter um comentário pelo ID.
    - [x]  Criar um repositório com o método necessário.
    - [x]  Criar um serviço com o método necessário.
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
