### ISSUE TITLE
[Backend - API - Atualizar Comentário] Como um usuário, quero poder atualizar um comentário.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/SQUAD-14#15]
**Descrição:**
Usuários devem poder atualizar o conteúdo de um comentário existente.

**Critérios de Aceitação:**

- A API deve aceitar uma requisição PUT com o novo conteúdo para um ID específico.
- A API deve validar que o conteúdo não está vazio.
- A API deve confirmar que o comentário foi atualizado.

**Tasks:**

- [x]  Criar DTO para a requisição (opcional).
- [x]  Implementar o endpoint PUT para atualização de comentários.
    - [x]  Criar um repositório com o método necessário.
    - [x]  Criar um serviço com o método necessário.
    - [x]  Criar controller com o endpoint necessário.
- [x]  Implementar validações para o conteúdo.
- [x]  Atualizar a documentação da API.
