### ISSUE TITLE
[Backend - API - Listar Comentários] Como um usuário, quero ver todos os comentários de uma publicação específica.

### ISSUE THREAD

**Issue by fariassilva** [Hanami-Staff/SQUAD-14#17]
**Descrição:**
O sistema deve permitir que qualquer pessoa visualize todos os comentários existentes para uma publicação específica. A listagem deve incluir ID, conteúdo e data de criação de cada comentário.

**Critérios de Aceitação:**

- A API deve aceitar uma requisição GET para listar todos os comentários de uma publicação.
- A API deve retornar uma lista de todos os comentários com seus detalhes.

**Tasks:**

- [x]  Criar DTO para a requisição (opcional).
- [x]  Implementar o endpoint GET para listagem de comentários.
    - [x]  Criar um repositório com o método necessário.
    - [x]  Criar um serviço com o método necessário.
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
