### ISSUE TITLE
[Backend - API - Excluir Comentário] Como um usuário, quero deletar um comentário.

### ISSUE THREAD

**Issue by Lphilipex** [Hanami-Staff/SQUAD-14#18]
**Descrição:**
Usuários devem poder deletar um comentário.

**Critérios de Aceitação:**

- A API deve aceitar uma requisição DELETE para um ID específico.
- A API deve confirmar que o comentário foi deletado.

**Tasks:**

- [x]  Implementar o endpoint DELETE para deleção de comentários.
    - [x]  Criar um repositório com o método necessário.
    - [x]  Criar um serviço com o método necessário.
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
