### ISSUE TITLE
[Backend - API - Obter Uma Publicação] Como um usuário, quero ver detalhes de uma a publicação específica.

### ISSUE THREAD

**Issue by 1Jeferson** [Hanami-Staff/SQUAD-14#3]
***Descrição:***
O sistema deve permitir que qualquer pessoa visualize detalhes de uma publicação específica existente. A listagem deve incluir campos com mais detalhes da publicação.

***Critérios de Aceitação:***

- A API deve aceitar uma requisição GET para listar uma publicação de um ID específico.
- A API deve retornar a publicação escolhida com os detalhes.

***Tasks:***

- [x]  Criar DTO para a requisição (opcional)
- [x]  Implementar o endpoint GET para obter uma postagem pelo ID;
    - [x]  Criar um repositório com o método necessário;
    - [x]  Criar um serviço com o método necessário;
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
