### ISSUE TITLE
[Backend - API - Atualizar Publicação] Como um usuário, quero poder atualizar uma publicação.

### ISSUE THREAD

**Issue by RabbitDeWitt** [Hanami-Staff/SQUAD-14#5]
***Descrição:***
Usuários devem poder atualizar o título e o conteúdo de uma publicação existente.

***Critérios de Aceitação:***

- A API deve aceitar uma requisição PUT com título e conteúdo para um ID específico.
- A API deve validar que nem o título nem o conteúdo estejam vazios.
- A API deve confirmar que a postagem foi atualizada.

***Tasks:***

- [x]  Criar DTO para a requisição (opcional)
- [x]  Implementar o endpoint PUT para atualização de publicações.
    - [x]  Criar um repositório com o método necessário;
    - [x]  Criar um serviço com o método necessário;
    - [x]  Criar controller com o endpoint necessário.
- [x]  Implementar validações para título e conteúdo.
- [x]  Atualizar a documentação da API.
