### ISSUE TITLE
[Backend - API - Excluir Publicação] Como um usuário, quero deletar uma publicação.

### ISSUE THREAD

**Issue by Lphilipex** [Hanami-Staff/SQUAD-14#7]
***Descrição:***
Usuários devem poder deletar uma publicação.

***Critérios de Aceitação:***

- A API deve aceitar uma requisição DELETE para um ID específico.
- A API deve confirmar que a publicação foi deletada.

***Tasks:***

- [x]  Implementar o endpoint DELETE para deleção de publicações.
    - [x]  Criar um repositório com o método necessário;
    - [x]  Criar um serviço com o método necessário;
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
