### ISSUE TITLE
[Backend - API - Listar Publicações] Como um usuário, quero ver todos as publicações disponíveis.

### ISSUE THREAD

**Issue by alessandrofarias** [Hanami-Staff/SQUAD-14#8]
***Descrição:***
O sistema deve permitir que qualquer pessoa visualize todos as publicações existentes. A listagem deve incluir ID, título, conteúdo e data de criação.

***Critérios de Aceitação:***

- A API deve aceitar uma requisição GET para listar todos as publicações.
- A API deve retornar uma lista de todos as publicações com seus detalhes.

***Tasks:***

- [x]  Criar DTO para a requisição (opcional)
- [x]  Implementar o endpoint GET para listagem de publicações.
    - [x]  Criar um repositório com o método necessário;
    - [x]  Criar um serviço com o método necessário;
    - [x]  Criar controller com o endpoint necessário.
- [x]  Atualizar a documentação da API.
